apiVersion: 1

datasources:
  - name: TimeGrid MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: zeek_logs
    user: zeek_user
    secureJsonData:
      password: zeek_password
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    isDefault: true
    editable: true
